site_name: Game da Cidadania
site_url: https://requisitos-de-software.github.io/2025.2-Grupo07/
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo07
repo_name: 2025.2-Grupo07
theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/icon.png
  favicon: images/icon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    #- content.action.edit
    #- content.action.view

nav:
  - Início: index.md
  - Análise: Análise.md
  - Elicitação: Elicitação.md
  - Modelagem: Modelagem.md
  - Apresentações: Apresentações.md
  - Planejamento: Planejamento.md
  - Pré-Rastreabilidade:
    - Pré-rastreabilidade/AppsAnalisados.md
    - Pré-rastreabilidade/RichPicture.md
  - Pós-Rastreabilidade: Pós-rastreabilidade.md
  - Termos de Uso: TermosDeUso.md
  - Heatmap: Heatmap.md

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

