site_name: Loterias Caixa
site_url: https://requisitos-de-software.github.io/2025.2-Grupo07/
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo07
repo_name: GitHub

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/icon2.1.png
  favicon: images/icon2.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    #- content.action.edit
    #- content.action.view

extra_css:
  - stylesheets/extra.css

nav:
  - Início: index.md
  - Planejamento: 
    - Planejamento/Cronogramas.md
    - Planejamento/Tabela de contribuição.md
    - Planejamento/Heatmap.md
    - Planejamento/Ferramentas.md
    - Planejamento/Metodologia.md
  - Pré-Rastreabilidade:
    - Pré-rastreabilidade/AppsAnalisados.md
    - Pré-rastreabilidade/RichPicture.md    
  - Elicitação: 
    - Elicitação/Brainstorm.md
    - Elicitação/Entrevista.md
    - Elicitação/Questionário.md
    - Elicitação/Personas.md
    - Elicitação/Storytelling.md
    - Elicitação/Introspecção.md
  - Modelagem: 
    - Modelagem/Casos de uso.md
    - Modelagem/Cenários.md
    - Modelagem/Especificação.md
    - Modelagem/História de usuário.md
    - Modelagem/Léxicos.md
    - Modelagem/NFR.md 
  - Análise:    
  
    - Análise/grupo 1RP.md
    - Análise/grupo 7RP.md

  - Pós-Rastreabilidade: 
    - Pós-rastreabilidade/Forward from.md
    - Pós-rastreabilidade/Backward from.md
  - Apresentações: Apresentações.md
  - Atas:
    - Atas/Ata de reunião 1.md
    - Atas/Ata de reunião 2.md
  - Termos de Uso: TermosDeUso.md

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark
