site_name: Loterias Caixa
site_url: https://requisitos-de-software.github.io/2025.2-Grupo07/
repo_url: https://github.com/Requisitos-de-Software/2025.2-Grupo07
repo_name: GitHub

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  logo: images/icon2.1.png
  favicon: images/icon2.png

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.mark

nav:
  - Início: index.md

  - Planejamento: 
    - Planejamento/Cronogramas.md
    - Planejamento/Tabela de contribuição.md
    - Planejamento/Heatmap.md
    - Planejamento/Ferramentas.md
    - Planejamento/Metodologia.md
  
  - Pré-Rastreabilidade:
    - Pré-rastreabilidade/AppsAnalisados.md
    - Pré-rastreabilidade/RichPicture.md    
    - Pré-rastreabilidade/Aplicativo Escolhido.md    
  
  - Elicitação: 
    - Perfil de Usuário: Elicitação/Perfil de Usuário.md
    - Personas: Elicitação/Personas.md
    - Técnicas:
      - Entrevista: Elicitação/Técnicas/Entrevista.md
      - Observação: Elicitação/Técnicas/Observação.md
      - Glossário: Elicitação/Técnicas/Glossário.md
    - Priorização:
      - MoSCoW: Elicitação/MoSCoW.md
      - $100: Elicitação/$100.md
      - Three level scale: Elicitação/Three level scale.md
      - Value, Cost and Risk: Elicitação/Value, Cost and Risk.md

  - Modelagem: 
    - Modelagem/Casos de uso.md
    - Modelagem/Cenários.md
    - Modelagem/Especificação.md
    - Modelagem/História de usuário.md
    - Modelagem/Léxicos.md
    - Modelagem/NFR.md 
  
  - Análise:   
    - Análise/grupo 1RP.md
    - Análise/grupo 7RP.md

  - Pós-Rastreabilidade: 
    - Pós-rastreabilidade/Forward from.md
    - Pós-rastreabilidade/Backward from.md
  
  - Apresentações: Apresentações.md
  
  - Atas:
    - Atas/Ata de reunião 1.md
    - Atas/Ata de reunião 2.md
  
  - Termos de Uso: TermosDeUso.md

